### ISSUE TITLE
tests fail? Also, question

### ISSUE THREAD

**Issue by StevenACoffman** [johanbrandhorst/grpc-postgres#21]
**Question:** So is the intent here that each parallel test will **reuse** the same docker container PostgreSQL instance(on host port 5432) with migrations applied, or is it that each test will get a **new, separate**  container PostgreSQL instance on an ephemeral host port?

Also, it might just be that I'm on darwin, but it looks like the tests are failing for me. I pinned golang.org/x/sys@f9321e4c35 to get past one hurdle, but got some other trouble:
```
$ go test users/users_test.go
# github.com/ory/dockertest/v3/docker/pkg/term
../../../go/pkg/mod/github.com/ory/dockertest/v3@v3.6.0/docker/pkg/term/tc.go:13:28: undefined: unix.SYS_IOCTL
../../../go/pkg/mod/github.com/ory/dockertest/v3@v3.6.0/docker/pkg/term/tc.go:18:28: undefined: unix.SYS_IOCTL
../../../go/pkg/mod/github.com/ory/dockertest/v3@v3.6.0/docker/pkg/term/termios_bsd.go:24:31: undefined: unix.SYS_IOCTL
../../../go/pkg/mod/github.com/ory/dockertest/v3@v3.6.0/docker/pkg/term/termios_bsd.go:37:31: undefined: unix.SYS_IOCTL
FAIL	command-line-arguments [build failed]
FAIL

steve@Stevens-MBP: ~/Documents/git/grpc-postgres on master [!]
$ go get golang.org/x/sys@f9321e4c35
go: finding golang.org/x/sys f9321e4c35

steve@Stevens-MBP: ~/Documents/git/grpc-postgres on master [!]
$ go test users/users_test.go
# command-line-arguments_test [command-line-arguments.test]
users/users_test.go:58:4: tb.Cleanup undefined (type testing.TB has no field or method Cleanup)
users/users_test.go:84:4: tb.Cleanup undefined (type testing.TB has no field or method Cleanup)
users/users_test.go:125:3: t.Cleanup undefined (type *testing.T has no field or method Cleanup)
users/users_test.go:133:3: t.Cleanup undefined (type *testing.T has no field or method Cleanup)
users/users_test.go:195:3: t.Cleanup undefined (type *testing.T has no field or method Cleanup)
users/users_test.go:203:3: t.Cleanup undefined (type *testing.T has no field or method Cleanup)
users/users_test.go:346:3: t.Cleanup undefined (type *testing.T has no field or method Cleanup)
users/users_test.go:354:3: t.Cleanup undefined (type *testing.T has no field or method Cleanup)
users/users_test.go:396:3: b.Cleanup undefined (type *testing.B has no field or method Cleanup)
users/users_test.go:404:3: b.Cleanup undefined (type *testing.B has no field or method Cleanup)
users/users_test.go:404:3: too many errors
FAIL	command-line-arguments [build failed]
FAIL
```

**Comment by johanbrandhorst** [comment]
Heh, I hadn't noticed this failure because it only affects Mac. See https://github.com/ory/dockertest/issues/208. I'll pin to the workaround version until there's a fix.

To answer your specific questions;

> So is the intent here that each parallel test will reuse the same docker container PostgreSQL instance(on host port 5432) with migrations applied, or is it that each test will get a new, separate container PostgreSQL instance on an ephemeral host port?

If you jump into the tests, you can see that each test calls to `startDatabase`. Each call to `startDatabase` starts a separate postgres container and returns its URL. So each top-level test has its own postgres instance. So it is the latter.

> Also, it might just be that I'm on darwin, but it looks like the tests are failing for me. I pinned golang.org/x/sys@f9321e4c35 to get past one hurdle, but got some other trouble:

The errors you're seeing is because of a new feature in Go 1.14: https://www.gopherguides.com/articles/test-cleanup-in-go-1-14/. Just upgrade to 1.14 and that error will go away :smile:.
