### ISSUE TITLE
Idea for proto-sql consistency and avoid duplicated struct?

### ISSUE THREAD

**Issue by i9** [johanbrandhorst/grpc-postgres#23]
Thanks for the nice demo!

I'd like to know if you have thought about:
1. Avoid two user struct from pb and sqlc
2. How to keep proto and sql in sync 

I'm thinking sqlc may need to support an alias struct mode so in models.go it's just type alias to pb.go struct. And we could add proto fieldoptions to generate schema.sql automatically. So proto is the only source of truth.

**Comment by StevenACoffman** [comment]
Consider checking out [jmattheis/goverter](https://github.com/jmattheis/goverter) was designed to translate between sqlc / gqlgen / pb / [oapi-codegen](https://github.com/deepmap/oapi-codegen) to avoid the boilerplate translation.

**Comment by johanbrandhorst** [comment]
Hi Junda,

My general answer to this question is that it's not such a bad thing that these types are separate - I like having the distinction between persistence types and API layer types as they may evolve separately. For example, you may want to change what a field looks like in the API but you may not want to make the same change to the database schema, or vice versa. I like that `sqlc` and `protobuf` can do the generation from the "IDL"s in both cases, being the protobuf schema and the SQL schema respectively.

What do you think?

**Comment by i9** [comment]
Thanks for the answer! Sorry I was busy w/ our recent launch.
I agree having separate struct definitions can optimize for each use case persistence vs. API interaction, as long as the fields are compatible. As the data layer should be relatively stable, as long as the engineer making changes are aware of the implication, it should be fine.

Thanks again!
